import React from "react";
import Header from "../components/Header";
import Footer from "./Footer";
import { Box } from "@mantine/core";
import Head from "next/head";
import { motion } from "framer-motion";

const Layout = ({ children }) => {
	return (
		<div>
			<Head>
				<title>Comic Strip</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 3 }}>
				<Header />
			</motion.div>
			<Box my="10vh" />
			{children}
			<motion.div
				initial={{ y: 200, opacity: 0 }}
				whileInView={{ y: 0, opacity: 1 }}
				viewport={{ once: true }}
				transition={{ duration: 0.7 }}
			>
				<Footer />
			</motion.div>
		</div>
	);
};

export default Layout;
